version: "3.5"

services:
  api01: &api
    image: alanviana/rinha-de-backend-2024-q1-ktor:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_DATABASE=rinha-database
      - DB_USER=postgres
      - DB_PASSWORD=admin
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - DB_DATABASE=rinha-database
      - DB_USER=postgres
      - DB_PASSWORD=admin
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha-database
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
